apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token

metadata:
  name: spring-app-hello-world-service-account-secret
  annotations:
    kubernetes.io/service-account.name: spring-app-hello-world-sa
